version: "3"

networks:
  default:
    ipam:
      config:
        - subnet: 160.25.100.0/24

services:
  elasticsearch-master:
    container_name: elasticsearch-master
    image: elasticsearch:7.16.2
    restart: always
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms32m -Xmx192m"
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      default:
        ipv4_address: 160.25.100.2

  zinc:
    container_name: zinc
    image: public.ecr.aws/zinclabs/zinc:latest
    restart: always
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: password
      ZINC_DATA_PATH: /data
    expose:
      - 4080
    ports:
      - "4080:4080"
    networks:
      default:
        ipv4_address: 160.25.100.3